import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const inter = Kanit({ weight: '400',subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ระบบบริการการศึกษา : มหาวิทยาลัยพะเยา",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
